listening-port=3478
min-port=49152
max-port=49172
realm=devicehub
user=devicehub:turnpassword123
no-tls
no-dtls
no-multicast-peers
fingerprint
no-tcp-relay
verbose
external-ip=192.168.1.107/172.20.0.21
